# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Blog do Ninito
description: >- # this means to ignore newlines until "baseurl:"
  Tenho um gato chamado Opala e outro gato chamado Chevette.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://victormf2.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: victormf2
name: Victor Machado
repository: victormf2/blog
author:
  name: Victor Machado
  avatar: "/assets/img/profile.jpg"
  bio: "Tenho um gato chamado Opala e outro gato chamado Chevette."
  location: "São Paulo"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/victormf2"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/victor-machado-de-franca"

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: sunrise
locale: pt-BR
date_format: "%-d de %B de %Y"
enable_copy_code_button: true
atom_feed:
  hide: true
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/victormf2/blog"
date_locale: pt
search: true
lunr:
  search_within_pages: true

plugins:
  # - jekyll-feed
  - jekyll-date-localization
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - license.html
  - README.md
  - serve.ps1
  - scripts/

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
      show_date: true
